### PR TITLE
feat: DEV-4081: Magic Wand tool

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1132

### CODE REVIEW

**Review by AndrejOros — APPROVED** [review]

**Comment by hlomzik** [comment]
/frontend build lfs master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4172510687)

**Comment by hlomzik** [comment]
/frontend help
> Command | Description
> --- | ---
> /frontend build           | Get build frontend static for all repos
> /frontend build lsf [sha] | Get build frontend static for heartexlabs/label-studio-frontend only
> /frontend build dm [sha]  | Get build frontend static for heartexlabs/dm2 only

**Comment by hlomzik** [comment]
/frontend build lfs master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4172852440)

**Comment by hlomzik** [comment]
/frontend build lsf master
> Successfully pushed new changes
>  heartexlabs/label-studio-frontend@18fc2e52136e5c2652dadb2659f44ef7625c8459
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4172923875)

**Review by hlomzik — APPROVED** [review]

**Pull request merged**
