### PR TITLE
feat: LSDV-3025-4: Filtered regions hidden

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @Travis1282!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1325

### CODE REVIEW

**Review by Travis1282 — APPROVED** [review]

**Review by juliosgarbi — APPROVED** [review]

**Review by nick-skriabin — APPROVED** [review]

**Review by MihajloHoma — APPROVED** [review]

**Comment by juliosgarbi** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4872994253)

**Comment by juliosgarbi** [comment]
/frontend build lsf master
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4873961132)

**Comment by juliosgarbi** [comment]
/frontend build lsf master
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4874453535)

**Comment by juliosgarbi** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-lsdv-3025-4/filted-regions-hidden (153d99e2499e40338776f55c515b36c6d08a5b44)
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4874460505)

**Comment by juliosgarbi** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4875312056)

**Pull request closed without merging**
