### PR TITLE
fix: get_predictions for tasks in projects without an ML backend

### PR DESCRIPTION
**Pull request by fvdnabee**
### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

I don't have a TICKET-ID I'm afraid.

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [x] Backend (API)
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_
Predictions aren't retrieved for tasks in projects without an ML backend. Tasks with (offline) pre-annotations have predictions without an ML backend. For these tasks annotators do not see the prediction suggestion when labeling.

Versions > 1.8.2post0 are impacted, bug fix should likely be back ported to 1.8.x. Users on impacted versions can revert to the old behavior by disabling the `ff_front_dev_1682_model_version_dropdown_070622_short` feature flag. Related PR that introduced this change: https://github.com/HumanSignal/label-studio/pull/4363

#### What does this fix?
_(if this is a bug fix)_
Missing task predictions for projects without an ML backend.

#### What is the new behavior?
_(if this is a breaking or feature change)_
When there are no model versions from an ML backend, then try the model version set in the project settings.

#### What is the current behavior?
_(if this is a breaking or feature change)_
Project model versions are ignored.

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [x] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

Backend tasks api.

### CODE REVIEW

**Comment by fvdnabee** [comment]
Any chance this could get triaged/reviewed? CC @makseq

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
