### PR TITLE
fix: TRIAG-600: Add missing storage title field to Redis config

### PR DESCRIPTION
**Pull request by jombooth**
[Re-created using `gh` command line tool for CI (mirror #5552]

This commit adds a required missing field to the Redis storage form -- the storage title. Without this field, the UI will throw an exception when trying to display the saved configuration's card. See [Slack](https://label-studio.slack.com/archives/CQ8LYQ0J2/p1709796798556099) for details.

Also fix the port showing up as `undefined` on the frontend's storage card. We'll need to make a similar change in LSE.

### CODE REVIEW

**Review by makseq — APPROVED** [review]

**Review by bmartel — APPROVED** [review]

**Comment by jombooth** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9506651972)
> Successfully merged:  1 file changed, 2 insertions(+), 1 deletion(-)

**Comment by jombooth** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9508004300)
> Successfully merged:  19 files changed, 20 insertions(+), 83 deletions(-)

**Comment by jombooth** [comment]
/git merge develop 
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9517302737)
> Successfully merged:  3 files changed, 62 insertions(+), 6 deletions(-)

**Comment by jombooth** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9518920497)
> Successfully merged:  35 files changed, 595 insertions(+), 870 deletions(-)

**Pull request merged**
