### PR TITLE
Release/0.2.1-5

### PR DESCRIPTION
**Pull request by shevchenkonik**
- Fixed Polygon's bugs
- Zoom image (Press Ctrl + mousedown/mouseup)
- Multilabeling fix bugs
- Reset button fix bugs
- Text Tag fix bugs
- Update styles
- Prepare time traveller for App

### CODE REVIEW

**Comment by VictorAtPL** [comment]
Good to see something in progressing with reference to Polygons. 😄

**Comment by shevchenkonik** [comment]
https://github.com/heartexlabs/label-studio/issues/102

**Comment by shevchenkonik** [comment]
https://github.com/heartexlabs/label-studio/issues/103

**Comment by shevchenkonik** [comment]
https://github.com/heartexlabs/label-studio/issues/87

**Comment by shevchenkonik** [comment]
https://github.com/heartexlabs/label-studio/issues/100

**Comment by VictorAtPL** [comment]
Are you going to fix also #104 or this Pull Request is ready to test and make code review?

**Comment by shevchenkonik** [comment]
@VictorAtPL 
#104 and other improvements with Zoom control will be in the next patch release. This one is ready for testing but you need to build frontend part of PR.

**Comment by VictorAtPL** [comment]
@shevchenkonik I pulled `release/0.2.1-5` branch and built frontend with `npm run build`, after that I run backend with `python3 server.py`.

Unfortunately #102 is still not solved. Please try to test it the same way I recorded it on screencast.
#103 fixed, 
#100 not fixed. When I add three polygons, save task, go back to it again, click reset, what should I get? By clicking reset polygons are removed from image, but not from the right side "Entity" panel. When I click a label then and try to annotate, it does not work (seems it may has something in common with #102).
#87 still broken. When building a polygon, sometime it allows to remove lastly added point, but sometimes the history stops only on one, sometime on more than one. It's not deterministic.

Do you want me to make a screencast again?

**Comment by shevchenkonik** [comment]
@VictorAtPL thank you, but no new screencast needed.

**Comment by shevchenkonik** [comment]
@VictorAtPL #100 and #87 will be in the next patch release.

**Pull request merged**
