### PR TITLE
fix: LEAP-149: Fix selected=true for Taxonomy

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1239
- https://github.com/HumanSignal/label-studio-frontend/pull/1239

### CODE REVIEW

**Review by juliosgarbi — APPROVED** [review]

**Review by Gondragos — APPROVED** [review]

**Comment by nikitabelonogov** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/5484574631)

**Comment by nikitabelonogov** [comment]
/frontend build lsf c592549d0c3a99f3223ef2e50035ae4efc2ceb3f
> Successfully pushed new changes
>  heartexlabs/label-studio-frontend@c592549d0c3a99f3223ef2e50035ae4efc2ceb3f
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/5484639779)

**Review by MihajloHoma — APPROVED** [review]

**Pull request merged**
