### PR TITLE
docs: Fix admonition rendering

### LINKED ISSUE #4538: Some markdown don't render correctly in the docs
**Describe the bug**
Pretty much everywhere in the docs where there are  `!!! note` or `!!! attention "important"` the markdown don't render.

**To Reproduce**
Check the following links: [install page](https://labelstud.io/guide/install.html#Install-with-Docker-on-nix) and [signup doc page](https://labelstud.io/guide/signup.html#Create-an-account)

**Screenshots**
Screenshot 2023-07-19 at 16 14 29
Screenshot 2023-07-19 at 16 13 47

**Environment:**
 Chrome Version 114.0.5735.198 (Official Build) (arm64) on Mac Os Ventura 13.4.1 (c)

### PR DESCRIPTION
**Pull request by huguestennier**
Fix https://github.com/heartexlabs/label-studio/issues/4538

### How to QA

These should all work now:

https://deploy-preview-4541--label-studio-docs-new-theme.netlify.app/guide/install.html#Install-with-Docker-on-nix
https://deploy-preview-4541--label-studio-docs-new-theme.netlify.app/guide/signup.html#Create-an-account

### CODE REVIEW

**Comment by ReDeiPirati** [comment]
Hey @huguestennier!

I also spotted [this other line](https://github.com/heartexlabs/label-studio/blob/53d978ff9e1245820ffe6c7fa959b6bf2965f097/docs/source/guide/signup.md?plain=1#L90-L91). After that looks good to me.

Thanks!

**Comment by hogepodge** [comment]
LGTM

**Review by bmartel — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Review by nick-skriabin — APPROVED** [review]

**Comment by sajarin** [comment]
@huguestennier can we resolve the conflicts here?

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
