### PR TITLE
fix: LSDV-5526: Fix duplication of classifications in LLM scenario

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @Gondragos!

This PR was created in response to a PRs in upstream repo:
- https://github.com/HumanSignal/label-studio-frontend/pull/1535

### CODE REVIEW

**Review by hlomzik — APPROVED** [review]

**Review by hlomzik — APPROVED** [review]

**Review by AndrejOros — APPROVED** [review]

**Comment by Gondragos** [comment]
/frontend build lsf
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6117259424)

**Comment by Gondragos** [comment]
/frontend build lsf 15267194e255c5770a6be5a59ab5e3a0d451d498
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6117270096)

**Comment by Gondragos** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-lsdv-5526/llm-interactive-fix (4ba5cd1dea8a4ae12e0001c575504eef9dbe71a8)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6121635246)

**Comment by nikitabelonogov** [comment]
/git merge develop

> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-lsdv-5526/llm-interactive-fix (6067228c7ed28f80bf455f8f127a0a2242ac96a1)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6121777553)

**Pull request merged**
