### PR TITLE
fix: LSDV-3004: Fix click on already assigned label

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1168

### CODE REVIEW

**Review by yyassi-heartex — APPROVED** [review]

**Review by discardedhunk — APPROVED** [review]

**Review by AndrejOros — APPROVED** [review]

**Comment by hlomzik** [comment]
/frontend build lsf
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4104674180)

**Comment by hlomzik** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4106949926)

**Comment by hlomzik** [comment]
already merged by https://github.com/heartexlabs/label-studio/pull/3576

**Pull request closed without merging**
