### PR TITLE
Read username and password from environment variables

### PR DESCRIPTION
**Pull request by triklozoid**

### CODE REVIEW

**Review by niklub — CHANGES_REQUESTED** [review]
Trying to create a new user with
```
docker run -it -p 8080:8080 -e LABEL_STUDIO_USERNAME=new@user.com -e LABEL_STUDIO_PASSWORD=12345678 -v mydata:/label-studio/data heartexlabs/label-studio:latest label-studio start
```
no luck..

also, do we support `label-studio` without start ?

**Comment by niklub** [comment]
Can we also add here
- username/password command line args populated from env to deploy/heroku_run.sh, and
- DISABLE_SIGNUP_WITHOUT_LINK, USERNAME, PASSWORD options into `app.json` under `"env"` section

**Comment by TimDeSmet** [comment]
@triklozoid do you have any status updates on this PR?

**Comment by triklozoid** [comment]
I tried run with docker: 
```
docker run -it -p 8080:8080 -e LABEL_STUDIO_USERNAME=new@user.com -e LABEL_STUDIO_PASSWORD=12345678 -v mydata:/label-studio/data heartexlabs/label-studio:latest label-studio start
``` 
and deploy to heroku
Screenshot_2021-04-29_10-14-54

**Review by niklub — APPROVED** [review]

**Pull request merged**
