### PR TITLE
chore: LSDV-4606: use Django migration to define indexes

### PR DESCRIPTION
**Pull request by jombooth**
### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [x] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

Creates indexes that were found to speed up next_task queries in production. The likely reason these queries provide speedups is that get_next_task calls `first()` in several places on tasks querysets, resulting in an order_by of `id` after the where clause has filtered by, eg, `project_id`. Examples:

https://github.com/HumanSignal/label-studio/blob/686c88ba45f91f0b30f2b626155896a2e2ee575e/label_studio/projects/functions/next_task.py#L284
https://github.com/HumanSignal/label-studio/blob/686c88ba45f91f0b30f2b626155896a2e2ee575e/label_studio/projects/functions/next_task.py#L172

An alternative approach to speeding up the dm/actions endpoint for next task actions would be to replace these `first` calls with `fast_first`, however, we know that these indexes are effective in practice for speeding up the endpoint.

indexes that were created by hand in prod:
```
 task_completion                                | project_anno_id                                                 | CREATE INDEX project_anno_id ON public.task_completion USING btree (project_id, id)
 task                                           | project_task_id                                                 | CREATE INDEX project_task_id ON public.task USING btree (project_id, id)
```

indexes created by migration:
```
 task_completion                         | task_comple_project_c7e507_idx                                  | CREATE INDEX task_comple_project_c7e507_idx ON public.task_completion USING btree (project_id, id)
 task                                    | task_project_7b1c80_idx                                         | CREATE INDEX task_project_7b1c80_idx ON public.task USING btree (project_id, id)
```

After deployment, we should drop `project_anno_id` and `project_task_id` indexes.

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

### CODE REVIEW

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LSDV-4606/next-task-indexes (f72a9c8539a41e5520891942abbdfda358ad857c)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6104853552)

**Review by bmartel — APPROVED** [review]

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LSDV-4606/next-task-indexes (ffdf135f7511e71b4474f144349df10f409fc7ed)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6112675092)

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LSDV-4606/next-task-indexes (649841c3fafcaafe454d590bfed7515e3d06c1ab)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6125183470)

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LSDV-4606/next-task-indexes (3c67f2e11356fb4450480e00340bbf9fe5ecca2d)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6149665670)

**Comment by jombooth** [comment]
Ran this code using @wesleylima 's requirements file from #4749 and got passes on postgresql, sqlite, and migrations tests:

https://github.com/HumanSignal/label-studio/actions/runs/6201794190/job/16839229715?pr=4746
https://github.com/HumanSignal/label-studio/actions/runs/6201794190/job/16839229195?pr=4746
https://github.com/HumanSignal/label-studio/actions/runs/6201794190/job/16839229887?pr=4746

**Pull request merged**
