### PR TITLE
docs: DOC-239: Add information about rectangle rotation

### PR DESCRIPTION
**Pull request by caitlinwheeless**
Add diagrams and clarifying information about rectangle rotation. 

This affects:

- [X] Community docs
- [X] Enterprise docs

### CODE REVIEW

**Comment by caitlinwheeless** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10533412925)
> Successfully merged:  delete mode 100644 web/libs/editor/src/components/VideoCanvas/VideoCanvas.styl

**Comment by caitlinwheeless** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10564147734)
> Successfully merged:  3 files changed, 9 insertions(+), 162 deletions(-)

**Review by hlomzik — APPROVED** [review]
I'd change "database" to "results" to reflect the way we work with data, not the way we store them. All the rest is great and really helpful, thank you!

**Review by hlomzik — APPROVED** [review]

**Comment by caitlinwheeless** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10570370704)
> Successfully merged: Already up to date.

**Comment by caitlinwheeless** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10582268389)
> Successfully merged:  17 files changed, 47 insertions(+), 144 deletions(-)

**Pull request merged**
