### PR TITLE
fix: OPTIC-79: Add queueTotal to lsfProperties from project

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @Travis1282!

This PR was created in response to a PRs in upstream repo:
- https://github.com/HumanSignal/dm2/pull/234
- https://github.com/HumanSignal/label-studio-frontend/pull/1554

### CODE REVIEW

**Comment by AndrejOros** [comment]
/git merge develop 
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6403452123)

**Review by AndrejOros — APPROVED** [review]

**Comment by bmartel** [comment]
/frontend build
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6471362433)

**Comment by bmartel** [comment]
/frontend build
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6473492127)

**Comment by bmartel** [comment]
/frontend build lsf
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6473503014)

**Review by bmartel — APPROVED** [review]

**Pull request merged**
