### PR TITLE
feat: LSDV-3936: Task history is stored on the backend

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @juliosgarbi!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/dm2/pull/150
- https://github.com/heartexlabs/label-studio-frontend/pull/1181

### CODE REVIEW

**Comment by juliosgarbi** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4174688995)

**Comment by juliosgarbi** [comment]
/frontend build lsf master
> Successfully pushed new changes
>  heartexlabs/label-studio-frontend@18fc2e52136e5c2652dadb2659f44ef7625c8459
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4174718283)

**Comment by juliosgarbi** [comment]
/frontend build dm master
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4174735195)

**Comment by juliosgarbi** [comment]
/frontend build lsf fb-lsdv-3936
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4174774196)

**Review by vladimirheartex — APPROVED** [review]

**Comment by juliosgarbi** [comment]
/frontend build lsf master
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4175969031)

**Comment by juliosgarbi** [comment]
/frontend build dm master
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4176105390)

**Pull request merged**
