### PR TITLE
feat: LSDV-5445: Add signout helper function for test cases

### PR DESCRIPTION
**Pull request by dredivaris**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend

### Describe the reason for change
This PR just adds a signout helper function for test cases (a test case used in LSE).  Its included here because its sister test helper, `signin` is also in LS so it made sense to implement them in the same file.  This code is used in this LSE PR: https://github.com/HumanSignal/label-studio-enterprise/pull/4538

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Tests

### CODE REVIEW

**Review by jombooth — APPROVED** [review]

**Review by bmartel — APPROVED** [review]

**Comment by dredivaris** [comment]
/frontend build [lsf/dm] master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/5907952526)

**Comment by dredivaris** [comment]
/frontend build dm master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/5928274319)

**Comment by nikitabelonogov** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-lsdv-5445 (9bcea3f9fb90d2df85b8e6f222092462ce68c3d4)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/5928274898)

**Pull request merged**
