### PR TITLE
docs: Small fixes for tag params doc

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/HumanSignal/label-studio-frontend/pull/1569

### CODE REVIEW

**Comment by hlomzik** [comment]
/frontend build editor master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6813957494)

**Comment by hlomzik** [comment]
/frontend build lsf master


> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6813976410)

**Comment by hlomzik** [comment]
/frontend build lsf master


> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6819369818)

**Comment by hlomzik** [comment]
/frontend build lsf 76fbbd83d0f9c52145bff1c9bf4c41f12d83a89c
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6819396238)

**Comment by nikitabelonogov** [comment]
/frontend build lsf 76fbbd83d0f9c52145bff1c9bf4c41f12d83a89c
> **Error**: failed to get build
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6840890128)

**Comment by nikitabelonogov** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6840908302)

**Comment by nikitabelonogov** [comment]
/frontend build lsf 76fbbd83d0f9c52145bff1c9bf4c41f12d83a89c


> Successfully pushed new changes
>  heartexlabs/label-studio-frontend@76fbbd83d0f9c52145bff1c9bf4c41f12d83a89c
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6840959578)

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
