### PR TITLE
feat: Visual improvements to aid labeling with the brush/eraser tool.

### PR DESCRIPTION
**Pull request by ZoutOP**
### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [*] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [*] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [*] Frontend

### Describe the reason for change
To help improve the speed of labeling lots of images quickly using the brush / eraser tool. This feature is useful conjoint with the SAM to predict object segmentations. The SAM model may not always give an exact result that is useful and often requires the user to use the brush or eraser to modify the selection. These changes help improve the speed at which the user is able to do this.

#### What does this fix?
Fixes the resizing of the cursor icon when the user changes it's brush sizes.
Reset the cursor to brush/eraser icon after leaving an existing region.
Shortcut key for smart tools correctly works.

#### What is the new behavior?
[Cursor] 
The mouse cursor for the brush and eraser tool have their Math.Round() to pixel coordinates removed. This allows the cursor position to be more accurate when using it zoomed. Before the paint of the brush would slightly off centered and did not allow for precise changes.
The cursor now correctly changes size to correspond the actual brush size when zooming in or out.
Because the cursor icon can have a maximum of 128 pixels, to denote any larger brush the icon circle will now be dotted at the maximum size to show it's larger than expected without implementing a div that tracks the mouse cursor instead.
[Brush/Eraser]
A opacity feature toggle has been added to settings to enable/disable stroke opacity when drawing with a stroke tool.
This adds a second slider tool next to the brush zoom tool to set an opacity value that is stored in local storage. This allows the user to set the opacity of the active brush area to any value they want while drawing. This makes it easier to see edges of an object while erasing / drawing when set to .2 opacity for example.
A fine stroke array has also been added to the brush which allows the brush to change in smaller steps when nearing it's smallest size. Currently the increase brush size or decrease size adds or removes 5 to the current size. Now when the brush is smaller than 10, and using the increment / decrement the size will be changed by 1 and below 5 by .5 each time. This allows for more finer details while zoomed in without having to use the slider tool and use the shortcuts instead.
When activating either stroke tool, if no area is selected it will select the last created one. This is especially useful when using the SAM model and have just accepted the prediction and now want to edit it with eraser or brush without having to select the region. The user can click either shortcut to enable the tool and it will select the last created region.
[Zoom]
Added a toggle to settings to invert the zoom direction. 
[Regions]
Added a toggle to settings that allows the user to hide all non active regions when annotating. This improves visibility when fine tuning their current drawing.
[Auto Annotation]
Smart tools created for the auto annotation now have their shortcut removed and instead can be selected using 'M' shortcut. This will toggle through the smart tools. However previous behaviour changed the tool as soon as the shortcut is clicked regardless if the tool was active. Now if the shortcut is clicked or the button when the smart tool is not currently active, it will remain the same and active the current tool. If the tool is active it will iterate between all tools like previous behaviour. This allows the user to use the stroke tool and then swap back to their last selected smart tool without having to skip through all of them.
The smart tool has extra shortcuts ['y'] and ['n'] to accept and reject the predicted annotations using a machine learning prediction. 
Added a toggle to the settings to turn of the 'Auto accept Annotationd Suggestings' that is always active above the image.

#### What is the current behavior?
See above.

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [*] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [*] integration
- [*] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_
Annotation
Settings
Controls\Shortcuts

### CODE REVIEW

**Comment by sajarin** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9388628134)
> Jira issue [TRIAG-602](https://humansignal.atlassian.net/browse/TRIAG-602) is created

[TRIAG-602]: https://humansignal.atlassian.net/browse/TRIAG-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sajarin** [comment]
hey @ZoutOP, I know it's been a while but thanks so much for the contribution! 

A couple of things: 
1. Can you fix the merge conflicts with the main branch? 
2. Is there any way you can provide some videos/looms of the visual improvements you're suggesting here? It's difficult to review all of the different changes and it'd help us measure the impact of the UI improvements. 

Let me know if you have any questions!

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
