### PR TITLE
docs: fix citation key

### PR DESCRIPTION
**Pull request by sudoLife**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [x] Docs have been added/updated (for bug fixes/features)

### Describe the reason for change
To ensure correct citation format easily importable into citation systems.

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### CODE REVIEW

**Comment by sajarin** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9388526920)
> Jira issue [TRIAG-595](https://humansignal.atlassian.net/browse/TRIAG-595) is created

[TRIAG-595]: https://humansignal.atlassian.net/browse/TRIAG-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sudoLife** [comment]
I believe in you guys :)

**Comment by sajarin** [comment]
hey @sudoLife, how does this help with citation systems?

**Comment by sudoLife** [comment]
> hey @sudoLife, how does this help with citation systems?

I was using Zotero when writing my thesis, and trying to import this citation entry into Zotero gave me errors due to the space in the citation key. After changing it to the current version, the import worked fine. Maybe it works okay as is with other systems like Mendeley, but the no-space version is a safe bet imo

**Review by caitlinwheeless — APPROVED** [review]

**Comment by caitlinwheeless** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9751606783)
> Successfully merged: Already up to date.

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
