### PR TITLE
chore: LSDV-4651,LSDV-4720: Cherry pick

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @juliosgarbi!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/dm2/pull/161

### CODE REVIEW

**Comment by farioas** [comment]
/frontend build dm fda7c008551b73019c361a4cb1b8bf9f4c66a01e
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4376388664)

**Comment by hlomzik** [comment]
/frontend help
> Command | Description
> --- | ---
> /frontend build           | Get build frontend static for all repos
> /frontend build lsf [sha] | Get build frontend static for heartexlabs/label-studio-frontend only
> /frontend build dm [sha]  | Get build frontend static for heartexlabs/dm2 only

**Comment by hlomzik** [comment]
/frontend build dm fda7c008551b73019c361a4cb1b8bf9f4c66a01e


> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4376577596)

**Comment by hlomzik** [comment]
/frontend build dm ls-release/1.7.2
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4376586876)

**Comment by hlomzik** [comment]
/frontend build dm ls-release/1.7.2
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4376707627)

**Comment by hlomzik** [comment]
/frontend build dm ls-release/1.7.2
> Successfully pushed new changes
>  heartexlabs/dm2@2ee2ddaf9596b9e600bbaf231768acd16815e498
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4377690474)

**Pull request merged**
