### PR TITLE
fix: OPTIC-1354: [Incident] Table locks in prod SaaS causing degraded performance

### PR DESCRIPTION
**Pull request by yyassi-heartex**
### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [x] Backend (API)
- [ ] Frontend

### Describe the reason for change
update annotation result_count on annotation save so we dont need to get the json to calculate count

### CODE REVIEW

**Comment by yyassi-heartex** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11902139346)
> Successfully merged:  create mode 100644 docs/scripts/tableOfContent.js

**Comment by yyassi-heartex** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11904230168)
> Successfully merged:  12 files changed, 124 insertions(+), 320 deletions(-)

**Review by makseq — CHANGES_REQUESTED** [review]
this should be covered with simple test at least

**Comment by yyassi-heartex** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11917525780)
> Successfully merged:  16 files changed, 277 insertions(+), 101 deletions(-)

**Review by bmartel — APPROVED** [review]

**Review by makseq — APPROVED** [review]

**Pull request merged**
