### PR TITLE
docs: Fix broken link

### LINKED ISSUE #5981: Anchor broken on the website
**Anchor broken**

On the page https://labelstud.io/guide/install

There is a broken link : 
https://labelstud.io/guide/install#Install-with-pip

Instead of :
https://labelstud.io/guide/install#Install-using-pip

### PR DESCRIPTION
**Pull request by STAR-173**
#### What does this fix?
Fixed Broken 'pip' Link in Install.md

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

### Describe the reason for change
fixes #5981 

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### CODE REVIEW

**Comment by sajarin** [comment]
hey @STAR-173, thanks for deciding to contribute to Label Studio! Unfortunately, I don't really see this as a change we need to make to the docs. So for that reason, I am closing this PR. 

If you have any questions or concerns, feel free to reach out to me via Slack and we can talk about some issues that might be more interesting to work on.

**Comment by sajarin** [comment]
reopening because of #5981

**Comment by sajarin** [comment]
Sorry for not understanding this change! Can you fix the broken link instead of changing the name of the section?

**Comment by STAR-173** [comment]
Sure, no problem

**Comment by STAR-173** [comment]
@sajarin Just pushed a new commit. You can review it now

**Review by makseq — APPROVED** [review]

**Pull request merged**
