### PR TITLE
docs: Add Starter Cloud to Prompts table

### PR DESCRIPTION
**Pull request by caitlinwheeless**
Starter Cloud supports Prompts, so adding it to that the table on the overview page

#### Change has impacts in these area(s)
_(check all that apply)_
- [X] Enterprise docs
- [ ] Community docs

### CODE REVIEW

**Review by shereezhang — APPROVED** [review]
thank you!

**Review by matt-bernstein — APPROVED** [review]

**Comment by matt-bernstein** [comment]
@caitlinwheeless is this ready to go?

@shereezhang is it worth mentioning here that current enterprise users should contact us to get Prompts turned on? Or are we changing that very soon?

**Comment by caitlinwheeless** [comment]
> @caitlinwheeless is this ready to go?
> 
> @shereezhang is it worth mentioning here that current enterprise users should contact us to get Prompts turned on? Or are we changing that very soon?

It's ready to go from my perspective - I think we were waiting for the feature flag to be turned on? I also just snuck in an unrelated change..... 

Will let @shereezhang answer the other thing.

**Comment by shereezhang** [comment]
ready to go! flipped the FF in prod

**Comment by shereezhang** [comment]
@matt-bernstein - since current enterprise users will have the prompts sneak preview in LSE, we can skip mentioning it in docs for now

**Pull request merged**
