### PR TITLE
fix: DEV-2072: Export for large projects leads to OOM and works very slowly

### PR DESCRIPTION
**Pull request by KonstantinKorotaev**

### CODE REVIEW

**Review by makseq — APPROVED** [review]

**Comment by JulesBelveze** [comment]
Any idea when this fix will be released? Or is there any workaround I can try to export my annotations without crashing the server?

**Comment by makseq** [comment]
@JulesBelveze This fix should be in the master already, so you can use the latest docker image or install LS from the latest master commit.

**Comment by JulesBelveze** [comment]
Hey @makseq I did pull the latest Docker image but I'm still hitting a "Server Error" when trying to export my project..

**Comment by KonstantinKorotaev** [comment]
@JulesBelveze could you please show the log of your server?

**Comment by JulesBelveze** [comment]
Hey @KonstantinKorotaev the only thing that I'm able to see from the container logs is this:
```
[2022-05-20 13:21:37,952] [ldclient.util::all_flags_state::367] [WARNING] all_flags_state() called, but client is in offline mode. Returning empty state
[2022-05-20 13:21:37,969] [django.request::log_response::224] [WARNING] Not Found: /.env
```

**Comment by JulesBelveze** [comment]
Is there a way (through the API or the UI) to only export a subset of tasks??

**Comment by makseq** [comment]
@JulesBelveze or you can check my answer here - https://github.com/heartexlabs/label-studio/issues/2419#issuecomment-1141445415

**Pull request merged**
