### PR TITLE
chore: LEAP-1090: django 4.2 upgrade (WIP)

### PR DESCRIPTION
**Pull request by jombooth**
Migrations generated because of changes in autodetector: https://docs.djangoproject.com/en/5.0/releases/4.0/#migrations-autodetector-changes

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Comment by triklozoid** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10248340643)
> Successfully merged:  695 files changed, 17036 insertions(+), 8472 deletions(-)

**Comment by triklozoid** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10282996018)
> Successfully merged:  create mode 100644 docs/themes/v2/source/images/project/scripts.png

**Comment by triklozoid** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10347993830)
> Successfully merged:  7 files changed, 14 insertions(+), 120 deletions(-)

**Review by wesleylima — APPROVED** [review]

**Comment by jombooth** [comment]
LGTM (I can't actually approve this in GH, as I am the original author)

**Comment by triklozoid** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10367313495)
> Successfully merged:  52 files changed, 587 insertions(+), 340 deletions(-)

**Comment by triklozoid** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10375361357)
> Successfully merged:  3 files changed, 9 insertions(+), 9 deletions(-)

**Pull request merged**
