### PR TITLE
ci: LEAP-1020: Relations panel improvements [INTERNAL]

### PR DESCRIPTION
**Pull request by hlomzik**
Mirror https://github.com/HumanSignal/label-studio/pull/5711 + small fixes to wording

### CODE REVIEW

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9454718287)
> Successfully merged:  567 files changed, 7228 insertions(+), 15885 deletions(-)

**Review by MihajloHoma — APPROVED** [review]

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9517801562)
> Successfully merged:  68 files changed, 1773 insertions(+), 434 deletions(-)

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9518020639)
> Successfully merged:

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9521580343)
> Successfully merged:  create mode 100644 label_studio/tests/sdk/test_ml.py

**Pull request merged**
