### PR TITLE
feat: DIA-1415: Add LabelConfig->ResponseModel generator

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @nikitabelonogov!

This PR was automaticaly generated via Follow Merge. 
Please ensure that all linked upstream Pull Requests are merged before proceeding with this one.

- https://github.com/HumanSignal/label-studio-sdk/pull/327 linked by [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11141717262)

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11141766661)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11141825977)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11144375260)

**Comment by niklub** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11344543660)
> Successfully merged:  229 files changed, 4282 insertions(+), 2223 deletions(-)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11344584152)

**Comment by niklub** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11364307490)
> Successfully merged:  20 files changed, 153 insertions(+), 88 deletions(-)

**Review by hakan458 — APPROVED** [review]

**Review by niklub — APPROVED** [review]

**Comment by niklub** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11441268675)
> Successfully merged:  45 files changed, 1187 insertions(+), 1403 deletions(-)

**Comment by nikitabelonogov** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11441556779)
> Successfully merged:  45 files changed, 1187 insertions(+), 1403 deletions(-)

**Review by niklub — APPROVED** [review]

**Pull request merged**
