### PR TITLE
fix: LSDV-4767: Use specific fields in api/projects/?ids= request

### PR DESCRIPTION
**Pull request by bmartel**
### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [X] Frontend

### Describe the reason for change
To alleviate the amount of data requested in the projects' queries, adding a `include=` with only the data that is absolutely required when loading second pass data with query param `ids=`.

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Projects List

### CODE REVIEW

**Review by AndrejOros — APPROVED** [review]

**Comment by bmartel** [comment]
/frontend help
> Command | Description
> --- | ---
> /frontend build           | Get build frontend static for all repos
> /frontend build lsf [sha] | Get build frontend static for heartexlabs/label-studio-frontend only
> /frontend build dm [sha]  | Get build frontend static for heartexlabs/dm2 only

**Comment by bmartel** [comment]
/git help
> Command | Description
> --- | ---
> /git merge `branch` | Merge branch `branch` into current branch

**Comment by bmartel** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4744087354)

**Comment by bmartel** [comment]
/frontend build
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4744204437)

**Pull request merged**
