### PR TITLE
docs: LSDV-4964: Remove old Ranker; fix docs

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1318

### CODE REVIEW

**Review by nick-skriabin — APPROVED** [review]

**Review by bmartel — APPROVED** [review]

**Comment by hlomzik** [comment]
/frontend help
> Command | Description
> --- | ---
> /frontend build           | Get build frontend static for all repos
> /frontend build lsf [sha] | Get build frontend static for heartexlabs/label-studio-frontend only
> /frontend build dm [sha]  | Get build frontend static for heartexlabs/dm2 only

**Comment by hlomzik** [comment]
/frontend build lsf
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4959065456)

**Comment by hlomzik** [comment]
/frontend build lsf master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4959094493)

**Pull request merged**
