### PR TITLE
chore: LSDV-4894: Update to NodeJS LTS

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @nicholasrq!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1323
- https://github.com/heartexlabs/dm2/pull/173

### CODE REVIEW

**Comment by nick-skriabin** [comment]
/frontend build lsf
> Already up-to-date. Nothing to commit.
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4734312308)

**Review by bmartel — APPROVED** [review]

**Review by farioas — APPROVED** [review]

**Comment by farioas** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4873464356)

**Comment by nikitabelonogov** [comment]
/git merge develop
> **Error**: failed to execute "merge" command
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4874060665)

**Comment by farioas** [comment]
/frontend build all master
> **Error**: failed to get build
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/4874424480)

**Pull request merged**
