### PR TITLE
fix: LEAP-514: Removed the ENABLE_MONOREPO_ENV environment variable and set monorepo files as default

### PR DESCRIPTION
**Pull request by juliosgarbi**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [x] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

### Describe the reason for change
In light of challenges faced while operating in a dual mode, this PR simplifies the environment by removing the `ENABLE_MONOREPO_ENV` variable. It also sets monorepo files as the default configuration to facilitate progress and unblock QA processes.

#### What does this fix?
This change simplifies the environment, reducing complexity and potential issues associated with the ENABLE_MONOREPO_ENV. It aims to enable smoother progress and ensure QA processes can proceed unimpeded.

#### What libraries were added/updated?
none

#### Does this change affect performance?
no

#### Does this change affect security?
no

#### What alternative approaches were there?
none

#### What feature flags were used to cover this change?
no

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### CODE REVIEW

**Comment by bmartel** [comment]
@juliosgarbi are we continuing to include the legacy artifacts from the separate repos, or is this now a clean cut with just the monorepo code?

**Comment by juliosgarbi** [comment]
> @juliosgarbi are we continuing to include the legacy artifacts from the separate repos, or is this now a clean cut with just the monorepo code?

That's a good question @bmartel! As we are not using this files anymore I'm going to open a ticket to plate team to stop include the legacy files on the LSO

**Review by bmartel — APPROVED** [review]

**Review by bmartel — APPROVED** [review]

**Comment by MihajloHoma** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7475201897)
> **Error**: failed to execute "build" command

**Comment by juliosgarbi** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7475236284)
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-leap-514 (14d84ed5bdbd2037033b9983b9e03e8175fba67f)

**Comment by juliosgarbi** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7475749103)
> Docker image was pushed with the tag

**Review by farioas — APPROVED** [review]

**Pull request merged**
