### PR TITLE
feat: DIA-1384: Estimate cost for an inference run

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @robot-ci-heartex!

This PR was automaticaly generated via Follow Merge. 
Please ensure that all linked upstream Pull Requests are merged before proceeding with this one.

- https://github.com/HumanSignal/label-studio-sdk/pull/330 linked by [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11156474025)

### CODE REVIEW

**Review by hakan458 — APPROVED** [review]

**Comment by pakelley** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11267833302)
> Successfully merged:  38 files changed, 406 insertions(+), 89 deletions(-)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11267860930)

**Comment by niklub** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11273090303)
> Successfully merged:  2 files changed, 30 insertions(+), 3 deletions(-)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11273131964)

**Comment by pakelley** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11274742647)
> Successfully merged: Already up to date.

**Pull request merged**
