### PR TITLE
fix: LEAP-184: Fix created_labels_drafts handling and improve error display

### PR DESCRIPTION
**Pull request by jombooth**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [x] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [x] Product design
- [ ] Backend (Database)
- [x] Backend (API)
- [x] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

Improve the confusing display when annotations or drafts block changes to the labeling config:

image

Also, delete task drafts along with annotation drafts when all annotations are deleted via Data Manager, and remove the drafts from project summary. Ensure drafts are removed from project summary when annotation-scoped AnnotationDraft objects are deleted due to the associated Annotation being saved/updated.

#### What is the current behavior?
_(if this is a breaking or feature change)_

image

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

### CODE REVIEW

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LEAP-184/drafts-cleanup-label-config-validation (d8a5f129e6f1cdd8cf6d1bde831c0ed3b861b858)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6268618319)

**Review by makseq — APPROVED** [review]

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LEAP-184/drafts-cleanup-label-config-validation (1c9d464e25bd6dae2a73598c41e0720641386662)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6279708965)

**Comment by AndrejOros** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LEAP-184/drafts-cleanup-label-config-validation (4501120b3c2ce6e8b0c22ee6f1961dfb47cd7f26)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6295664369)

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LEAP-184/drafts-cleanup-label-config-validation (769d0fe50df5b5143683714fa016ad93b522b493)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6319141439)

**Review by AndrejOros — APPROVED** [review]

**Comment by jombooth** [comment]
/git merge develop
> Successfully pushed new changes:
> Merge remote-tracking branch 'origin/develop' into fb-LEAP-184/drafts-cleanup-label-config-validation (4632aec14bd8f6c63d2e1fd1dd928288e6b04a72)
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/6343919244)

**Pull request merged**
