### PR TITLE
fix: DIA-989: LSF hotkeys being stuck when LSF is destroyed

### PR DESCRIPTION
**Pull request by nick-skriabin**
Whenever you enter Labeling Interface (Quick View, Label Stream, Labeling Settings), hotkeys assigned to labels and choices are not being unbound when you leave the given page. This sometimes causes an inability to input certain characters in other places of the app.

### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

#### What is the new behavior?
Auto-assigned hotkeys are now correctly unbound when leaving a page (LSF destroyed)

#### Does this change affect performance?
No

#### Does this change affect security?
No

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Frontend, Global

### CODE REVIEW

**Review by yyassi-heartex — APPROVED** [review]
wow nice catch with unbinding the hotkeys on destroy!

**Comment by nick-skriabin** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8880849597)
> Successfully merged:  1121 files changed, 59844 insertions(+), 61609 deletions(-)

**Comment by nick-skriabin** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8974090411)
> Successfully merged:  48 files changed, 2921 insertions(+), 339 deletions(-)

**Comment by nick-skriabin** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9007624451)
> Successfully merged:  448 files changed, 3270 insertions(+), 14683 deletions(-)

**Pull request merged**
