### PR TITLE
docs: (DEV-102 & DEV-1474)  Update all templates in documentation 

### PR DESCRIPTION
**Pull request by smoreface**
- Update templates to match the product.
- Add related tags and use case information for all templates.
- Update table of contents to use categories for all templates.

### CODE REVIEW

**Comment by makseq** [comment]
Duplicated configs? 
image

**Comment by smoreface** [comment]
> Duplicated configs? image

Oops, thanks! Thought I caught them all, must've missed one. Will do a pass through to check the others too.

**Comment by smoreface** [comment]
@hlomzik / @makseq / @niklub Please review this this week. Trying to get these incremental updates out as soon as possible.

**Comment by smoreface** [comment]
@makseq I'm going to add template previews to the rest of the templates in a future PR, and also will consider whether it makes more sense to have previews display the labeling interface or the interface with annotations. 

@niklub / @makseq please review this PR so that we can get these updates out in the world sooner!

**Review by makseq — APPROVED** [review]

**Pull request merged**
