### PR TITLE
feat: LEAP-452: FE Repo Modernization / Monorepo

### PR DESCRIPTION
**Pull request by juliosgarbi**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

### Describe the reason for change
The proposed change involves transitioning LabelStudio's frontend code from a multi-repository structure to a single mono-repository. This shift aims to simplify the existing setup by consolidating various repositories into one focused mono-repo. The orchestration and tooling of this new structure will be efficiently managed by NX.dev, a platform well-suited for mono-repo architectures. This move is expected to streamline development processes, reduce the need for repetitive tasks and complex configurations, and significantly lower the maintenance burden. Overall, this transition is designed to enhance the efficiency and manageability of LabelStudio's frontend codebase.

#### What libraries were added/updated?
[NX.dev](https://nx.dev/)

#### What alternative approaches were there?
One viable alternative approach for managing the frontend codebase was to utilize [Turborepo](https://turbo.build/), a modern build system optimized for JavaScript and TypeScript environments, especially in mono-repository contexts. However, following extensive discussions and collaborative deliberations with the entire frontend team, the decision was ultimately made to adopt NX.dev. This choice was based on a thorough evaluation of both platforms, considering various factors such as functionality, team familiarity, integration capabilities, and overall alignment with LabelStudio's project goals and long-term development strategy.

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)
- [x] Yes, and covered by env variable. To make the monorepo works you must set ENABLE_MONOREPO_ENV=1

### CODE REVIEW

**Comment by farioas** [comment]
/git merge develop
> **Error**: Merge conflict detected, please resolve it using the command line.
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7171105271)

**Comment by farioas** [comment]
/docker build
> Command | Description
> --- | ---
> /docker build | Build and push custom docker image
> **Error**: failed to execute "build" command
> 
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7171504019)

**Comment by farioas** [comment]
/docker build
> Command | Description
> --- | ---
> /docker build | Build and push custom docker image
> **Error**: failed to execute "build" command
> 
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7171673665)

**Comment by farioas** [comment]
/docker build
> Command | Description
> --- | ---
> /docker build | Build and push custom docker image
> Docker image build status: success
> Docker image was pushed with the tag develop
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7172087119)

**Comment by farioas** [comment]
/docker build
> Docker image build status: failure
> Docker image was pushed with the tag fb-leap-452
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7172896165)

**Comment by farioas** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7173018839)

**Comment by MihajloHoma** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7182693265)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7183145864)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7183291409)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7184565506)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7185921526)

**Comment by hlomzik** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7187597613)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7187911129)

**Comment by nikitabelonogov** [comment]
/docker build
> Docker image was pushed with the tag `fb-leap-452`
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7195819221)

**Comment by juliosgarbi** [comment]
/docker build
> **Error**: failed to execute "build" command
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7196875724)

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7198515094)
> **Error**: failed to execute "build" command

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7199674273)
> Docker image was pushed with the tag `fb-leap-452`

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7200321549)
> **Error**: failed to execute "build" command

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7203433873)
> Docker image was pushed with the tag `fb-leap-452`

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7203831425)
> Docker image was pushed with the tag `fb-leap-452`

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7203959656)
> Docker image was pushed with the tag `fb-leap-452`

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7209808495)
> Docker image was pushed with the tag ``

**Comment by farioas** [comment]
/docker build
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7211946242)
> Docker image was pushed with the tag `20231214.165007-fb-leap-452-ab7da4770`

**Review by bmartel — APPROVED** [review]

**Review by MihajloHoma — APPROVED** [review]

**Comment by juliosgarbi** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7263479054)

**Review by yyassi-heartex — APPROVED** [review]

**Pull request merged**
