### PR TITLE
refactor: OPTIC-482: Archive feature flag fflag_feat_optic_2_ensure_draft_saved_short

### PR DESCRIPTION
**Pull request by luarmr**
Remove feature flag fflag_feat_optic_2_ensure_draft_saved_short setting the value to true:

As usual, I recoment review the changes without whitespace diff:
https://github.com/HumanSignal/label-studio/pull/5673/files?diff=split&w=1

https://app.launchdarkly.com/default/production/features/fflag_feat_optic_2_ensure_draft_saved_short/targeting

Original ticket: https://humansignal.atlassian.net/browse/OPTIC-2

Screenshot 2024-04-03 at 4 27 49 PM

Screenshot 2024-04-03 at 4 28 01 PM

Screenshot 2024-04-03 at 4 28 15 PM

Screenshot 2024-04-03 at 4 28 28 PM

### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

### CODE REVIEW

**Comment by luarmr** [comment]
@bmartel I can use your help. 
I believe I may need to adjust label-studio-private as well. I can't find any chores here.

**Review by bmartel — APPROVED** [review]

**Comment by luarmr** [comment]
Thanks @bmartel for help with the repo I need to update.

**Comment by luarmr** [comment]
/git merge

> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8557983568)
> Successfully merged:  4 files changed, 34 insertions(+), 5 deletions(-)

**Comment by luarmr** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8572316198)
> Successfully merged:  39 files changed, 415 insertions(+), 145 deletions(-)

**Review by yyassi-heartex — APPROVED** [review]
good to see more FFs being removed 🎉

**Review by hlomzik — CHANGES_REQUESTED** [review]
We have to review the way we work with drafts as a whole. For now I'm blocking this PR until further investigation

**Comment by luarmr** [comment]
@hlomzik, I don't believe maintaining two branches of code FF on/off will positively help to address the issues with drafts

**Comment by luarmr** [comment]
@hlomzik will take care in other current ongoing efforts.

**Pull request closed without merging**
