### PR TITLE
feat: support Azure cloud storage  service principal authentication - expedite

### PR DESCRIPTION
**Pull request by machov**
### PR fulfills these requirements
* [x]  Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
* [x]  Tests for the changes have been added/updated (for bug fixes/features)
* [x]  Docs have been added/updated (for bug fixes/features)
* [x]  Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
* [x]  Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
* [ ]  Product design
* [x]  Backend (Database)
* [x]  Backend (API)
* [ ]  Frontend
### Describe the reason for change
For the moment, there is only an authentication through account key to Azure. The problem is that account key give a lot of rights on the storage that may not be necessary in order to perform readonly operations. 
#### What does this fix?
Now it is possible to have an azure integration that is based on a service principal.
#### What is the new behavior?
We have to create an app registration in Azure : 
We give this registration specific rights depending on what we want to do in labelstudio : 
In the UI, we create a new storage integration : 

#### What is the current behavior?
There is no impact on the previous behavior, it's just a new one.
#### What libraries were added/updated?
Azure Identity
#### Does this change affect performance?
Get a delegation key is quite slow, that's why there is :
* 24h cache for delegation key
* 15mn cache for sas token
There is a second minor change :
* When a "thumbnail" tag is present in the datarow, it will be used in the grid view
* When there is multiple layer in the image, the gridview will only render the first channel.
  (Today there is a buggy behavior).
#### Does this change affect security?
It should improve the security for people who just need specific rights on the container. **_For the moment, the "write" behavior have not been tested / developped on the container._**
#### What alternative approaches were there?
We can use an enterprise application and SSO in order to be linked to a user right and act on behalf of him.
#### What feature flags were used to cover this change?
None
### Does this PR introduce a breaking change?
_(check only one)_
* [ ]  Yes, and covered entirely by feature flag(s)
* [ ]  Yes, and covered partially by feature flag(s)
* [x]  No
* [ ]  Not sure (briefly explain the situation below)
### What level of testing was included in the change?
* [ ]  e2e
* [ ]  integration
* [x]  unit
### Which logical domain(s) does this change affect?
* Authentication
* UI

### CODE REVIEW

**Comment by makseq** [comment]
Is it a copy of https://github.com/HumanSignal/label-studio/pull/5765 ?

**Comment by machov** [comment]
yes, I also created a PR to @FrsECM  branch, I had created this PR to run the  CI pipeline, but never mind,  will move test this in our forks

**Comment by machov** [comment]
I also created a PR to @FrsECM  branch https://github.com/FrsECM/label-studio/pull/1

**Comment by machov** [comment]
I fixed some of the unit tests, I'm working on the unit tests that @makseq suggested in #5765

**Comment by machov** [comment]
tests are now passing, do you guys want to add this PR to the tests @makseq ?
image

**Comment by FrsECM** [comment]
Hi !
Why did you rollback secure encryption in db ?
Thanks,

**Comment by machov** [comment]
I was having issues with encryption/decryption at the time of testing credentials manually from the UI

I also thought not necessary cause the other Azure storage (key auth option)  is not encrypting keys and we are also popping secure fields out here
https://github.com/machov/label-studio/blob/4db9a11d5a822c3d7e5c7b4efe70fea890356564/label_studio/io_storages/azure_serviceprincipal/serializers.py#L25

**Comment by machov** [comment]
let me know what you think @FrsECM , we can also add them back

**Comment by machov** [comment]
I am not able to successfully create the storage upload below

```
- name: stage
  request:
    data:
      container: pytest-azure-images
      project: '{project_pk}'
      title: Testing Azure SPI storage (bucket from conftest.py)
      use_blob_urls: true
    method: POST
    url: '{django_live_url}/api/storages/azure_spi'
  response:
    save:
      json:
        storage_pk: id
    status_code: 201
```
since I get last_sync_count: 0 in the results. How is the bucket from "conftest.py" being uploaded?

- name: stage
  request:
    method: POST
    url: '{django_live_url}/api/storages/azure_spi/{storage_pk}/sync'
  response:
    json:
      last_sync_count: 0
    status_code: 200

**Comment by FrsECM** [comment]
> I was having issues with encryption/decryption at the time of testing credentials manually from the UI
> 
> I also thought not necessary cause the other Azure storage (key auth option) is not encrypting keys and we are also popping secure fields out here https://github.com/machov/label-studio/blob/4db9a11d5a822c3d7e5c7b4efe70fea890356564/label_studio/io_storages/azure_serviceprincipal/serializers.py#L25


I understand that testing with the UI may be an issue. To give you some context, at the beggining i didn't implement this but i did a security review within my company and i've been asked to make sure that credentials are not stored "clear" in the database.
For password, you do sha256 hash, because you have the hand on the verification process on the application side. But an account key is sensitive like if not more than the user password because a leak could not only impact labelling but the data.

A account key that is leaking is a risk that an attacker removes the data directly from the bucket what was not acceptable from our side.

That's why i implemented this quick fix for SPI, but of course it should be relevant the same way for AzureBlob Account key.

Because this credential have to be given to another provider, we can not only hash, we need to encrypt and decrypt, that's why i coded this this way, and in order to do this on the fly, i added this step in the "validation" function.

What is your position concerning that ?

Maybe it can be included in another PR but it should definitely be in your roadmap in order to improve security of your application.

**Comment by machov** [comment]
I try adding it back but Windows pytest fails for some reason https://github.com/machov/label-studio/actions/runs/9691945908/job/26745179790?pr=10

**Comment by machov** [comment]
For the current PR, I am not able to successfully create the pre-signed urls, any suggestions?

```
- name: stage
  request:
    method: GET
    url: '{django_live_url}/api/projects/{project_pk}/next'
  response:
    json:
      data:
        image_url: !re_match "/tasks/\\d+/presign/\\?fileuri=YXp1cmUtYmxvYjovL3B5dGVzdC1henVyZS1pbWFnZXMvYWJj"
    status_code: 200
```
this test above fails, the endpoint returns "azure-spi://<path/to/file>" instead of "/tasks/\\d+/presign/\\?fileuri=YX..."

**Comment by machov** [comment]
> For the current PR, I am not able to successfully create the pre-signed urls, any suggestions?
> 
> ```
> - name: stage
>   request:
>     method: GET
>     url: '{django_live_url}/api/projects/{project_pk}/next'
>   response:
>     json:
>       data:
>         image_url: !re_match "/tasks/\\d+/presign/\\?fileuri=YXp1cmUtYmxvYjovL3B5dGVzdC1henVyZS1pbWFnZXMvYWJj"
>     status_code: 200
> ```
> 
> this test above fails, the endpoint returns "azure-spi://<path/to/file>" instead of "/tasks/\d+/presign/\?fileuri=YX..."

I resolved this issue, all tests are passing now 🚀 🚀 🚀 

This storage authentication supports all types of Label studio inputs: presigned urls, blobs, and jsons. Any chance someone can take a look at this @makseq ? 🗡️  💯  😀

**Comment by machov** [comment]
anyone that can help with this @vegai @deppp @sajarin  ? this authentication would unblock projects in a lot of companies that only allow Service Principal to authenticate to Azure 👍

**Comment by machov** [comment]
ready to merge 😃 - [go to CI build](https://github.com/machov/label-studio/actions/runs/9849989992/job/27194778757)
image

**Comment by machov** [comment]
J’ai chiffré le mot passe @FrsECM

**Comment by machov** [comment]
I added the encryption to avoid storing passwords and have even more security. :)

**Comment by FrsECM** [comment]
Great to see it !

Just for my understanding. I saw that you replace blob urls by something like : 

´´´python
"azure_spi://container_name/blob_name"
´´´

It is the way you handle it as a standard in LStudio ?

**Comment by machov** [comment]
this is the expected behavior @FrsECM , i learned by setting s3 sync. Azure, GCP, and Redis also work this way with support for uris in json like <storage>://<account>/blob.

 label-studio supports different sources: a) json or b) blob. When it is a) json, it uses this convention of a json like {‘text’: ‘some_text’, ‘image’: uri}, when the uri is something like `s3://<bucket>/<blob>` ,  `azure-blob://<container>/<blob>` or in our case  `azure-spi://<container>/<blob>` then the backend resolves it to the actual blob url **https:/<account_name>.blob.core.windows.net/container/path/to/blob/<sas_token>**. This way it can load jsons with text predictions and annotations together with blobs like images. You can see azure-blob storage using account key also  supports this functionality and we are mirroring their tests. 

when it is b) blob , it will read all objects in the container as blobs using https:<account>.microsoft.dfs.com/path/to/blob/<sas_token’

this is explained in more detail here https://labelstud.io/guide/storage

**Comment by FrsECM** [comment]
In our case, we use azure and blob, it’s not dfs.


Then the url is something like that :

  *   https://<account name>.blob.core.windows.net/<container_name>/<path><sas_token>



How do you handle that case with azure_spi ?


Maybe it's worth adding an extra property on the storagemixin to define the type of storage/urls ?


Because with your url system you lose this information.

________________________________
De : Manrique Vargas ***@***.***>
Envoyé : Wednesday, July 10, 2024 7:43:22 AM
À : HumanSignal/label-studio ***@***.***>
Cc : François Ponchon ***@***.***>; Mention ***@***.***>
Objet : Re: [HumanSignal/label-studio] feat: Feature/azure service principal - expedite (PR #5926)


Yes, labelstudio supports different sources: a) json or b) blob. When it is a) json, it uses this convention of a json like {‘text’: ‘some_text’, ‘image’: uri}, when the uri is something like s3://<bucket>/<blob> , azure-blob://<container>/<blob> or in our case azure-spi://<container>/<blob> then the backend resolves it to the actual blob url https:<account>.microsoft.dfs.com/path/to/blob/<sas_token’

when it is b) blob , it will read all objects in the container as blobs using https:.microsoft.dfs.com/path/to/blob/<sas_token’

this is explained in more detail here https://labelstud.io/guide/storage

**Comment by machov** [comment]
There is no dfs involved.

Azure spi will create that https:// path

using this template `AZURE_ACCOUNT_URL_TEMPLATE = Template('https://${account_name}.blob.core.windows.net') `

- see https://github.com/machov/label-studio/pull/1/files#diff-5980155b1dd5224801ee19e315952534bef39171e7e27f55f4080d00ca871e57R228
- so if input is a json with uri , UI loads the blob from htttps: blob above
- If input is all url blobs  then also all blobs will be loaded form the https template above

**Comment by machov** [comment]
Both azure-blob and azure-spi will resolve the uri to the blob storage url
with a sas token:
*  https://<account
<https://urldefense.proofpoint.com/v2/url?u=https-3A__-253Caccount&d=DwQFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=vsizAKKZnU8VWlf1DcDvOg&m=UoCCIuhiLPiSvAAfg_miqx0t9IroNVLdkp-LX4X56GbnF2yRD_jgxT8ZphPj6XOi&s=U_h5YjF9NSRAW8sDR_jRfMlcxMLgWbqgl0M8m7CtQmM&e=>
 name>.blob.core.windows.net/<container_name>/<path><sas_token>

No dfs involved sorry for the confusion

**Comment by FrsECM** [comment]
Ok good !

I’ll try to test it because in my original implementation i didn’t do the same way.
Thanks !

**Comment by machov** [comment]
I ended up removing the encryption settings from the PR, @FrsECM  cause the UI is still having some trouble with it, this was my last attempt to add the encryption in this separate branch https://github.com/machov/label-studio/tree/dev/man/add_sp

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
