### PR TITLE
fix: DEV-4085: Fix error during submit

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @hlomzik!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1124

### CODE REVIEW

**Review by discardedhunk — APPROVED** [review]

**Review by Travis1282 — APPROVED** [review]

**Review by AndrejOros — APPROVED** [review]

**Review by nicholasrq — APPROVED** [review]

**Comment by csaroff** [comment]
Our annotation team is running into this right now. How long until it makes it to a stable docker image release version?

**Comment by hlomzik** [comment]
already merged by #3391

**Comment by csaroff** [comment]
> Our annotation team is running into this right now. How long until it makes it to a stable docker image release version?

@hlomzik

**Comment by hlomzik** [comment]
@csaroff I asked you in [LSF PR](https://github.com/heartexlabs/label-studio-frontend/pull/1124), duplicating it here:
> @csaroff what the problem exactly? Just annoying error or you have duplicated annotations after this as well? What steps do you use for this?

and this fix is already in LS develop, so you can check it.

**Comment by csaroff** [comment]
Sorry, missed that. A member of our annotation team reported that dozens of tasks that they completed weren't saved after clicking submit.

They also reported seeing the error addAnnotationToTaskHistory is not a function error. They didn't report duplicates afterward, but I didn't double-check either.

These seem like separate issues, but I don't have any further info on the task completions not saving.

**Comment by hlomzik** [comment]
Duplication could've happened because of this error, because submit became broken after it. Bow error is fixed, so I hope you won't have this problem anymore.

**Pull request closed without merging**
