### PR TITLE
fix: DIA-1508: Fix sdk to support Prompts MultiSkill

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @niklub!

This PR was automaticaly generated via Follow Merge. 
Please ensure that all linked upstream Pull Requests are merged before proceeding with this one.

- https://github.com/HumanSignal/label-studio-sdk/pull/342 linked by [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11459548152)

### CODE REVIEW

**Review by hakan458 — APPROVED** [review]

**Review by hakan458 — APPROVED** [review]

**Review by niklub — APPROVED** [review]

**Comment by niklub** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11516979294)
> Successfully merged:  245 files changed, 936 insertions(+), 524 deletions(-)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11517017413)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11517017413)

**Comment by farioas** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11517328872)
> Successfully merged: Already up to date.

**Pull request merged**
