### PR TITLE
ML page, tutorial & cold-start predicts

### PR DESCRIPTION
**Pull request by niklub**

### CODE REVIEW

**Comment by nabinkhadka** [comment]
What is the intention behind having "Import data" file uploader in the model setup page? @makseq @niklub

**Comment by makseq** [comment]
@nabinkhadka you can check your model using it. Just drag & drop file there and prediction will be generated immediately.

**Comment by nabinkhadka** [comment]
Will the data be a new task and saved? Will the predictions be saved?

**Comment by makseq** [comment]
Yes, it will be a new task and prediction will be saved.

**Comment by nabinkhadka** [comment]
Ah.. Basically it's a shortcut to import tasks, nothing to do with pred/model. As the predictions are generated only when moved to the tasks page. Right @makseq

**Comment by makseq** [comment]
@nabinkhadka It imports a task and then forcibly run the prediction for this task.

**Pull request merged**
