### PR TITLE
feat: RND-100: Labeling interface enhancements

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @niklub!

This PR was [created](https://github.com/HumanSignal/label-studio/actions/runs/9567599969) in a response to PRs in upstream repos:
- https://github.com/HumanSignal/label-studio-sdk/pull/248

### CODE REVIEW

**Comment by niklub** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/9604299421)
> Successfully merged:  4 files changed, 173 insertions(+), 100 deletions(-)

**Comment by farioas** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10581409310)
> Successfully merged:  889 files changed, 26398 insertions(+), 19260 deletions(-)

**Comment by farioas** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10681261880)
> Successfully merged:  395 files changed, 6699 insertions(+), 9047 deletions(-)

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
