### PR TITLE
feat: dino support

### PR DESCRIPTION
**Pull request by shondle**
A draft PR adding trying to make it possible to use dropdown menu in label studio project to send text context to all tasks selected.

### CODE REVIEW

**Comment by shondle** [comment]
Issue is I can send text context and retrieve prediction if I only select one task, but if I select multiple tasks before retrieving predictions the context is not sent and is run into an error.

**Comment by shondle** [comment]
Here is an example. It works on using context and retrieving prediction on one image. However, when I select multiple, it ends up retrieving no predictions and the ML backend shows a no context received (context is null) error so it cannot access the text prompt. 

https://github.com/HumanSignal/label-studio/assets/106922533/d3c83f29-c563-4c91-8f3e-99ec9742c60a

**Comment by shondle** [comment]
Earlier context errors have been fixed

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by ejiang-eog** [comment]
will this be merged soon?

**Comment by robot-ci-heartex** [comment]
This PR is stale because it has been open 45 days with no activity. Remove `stale` label or comment or this will be closed in 10 days.

**Comment by robot-ci-heartex** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Pull request closed without merging**
