### PR TITLE
fix: LSDV-4620-3: Fix Richtext performance and functional

### PR DESCRIPTION
**Pull request by robot-ci-heartex**
Hi @Gondragos!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/label-studio-frontend/pull/1297
- https://github.com/heartexlabs/dm2/pull/215

### CODE REVIEW

**Comment by Gondragos** [comment]
/ff update
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/5267290633)

**Review by bmartel — APPROVED** [review]

**Review by MihajloHoma — APPROVED** [review]

**Pull request merged**
