### PR TITLE
fix: DEV-3919: Set display flex to configure preview to show all content

### PR DESCRIPTION
**Pull request by juliosgarbi**

### CODE REVIEW

**Review by bmartel — APPROVED** [review]

**Review by MihajloHoma — APPROVED** [review]

**Comment by hlomzik** [comment]
/frontend build lsf
> Successfully pushed new changes
>  heartexlabs/label-studio-frontend@c538eb721831a45d3c77b25a4a8d6437872b1ad7
>
> [Workflow run](https://github.com/heartexlabs/label-studio/actions/runs/3949999943)

**Pull request merged**
