### PR TITLE
feat: LEAP-1533: Make Quick View readonly by condition

### PR DESCRIPTION
**Pull request by hlomzik**
When org field `read_only_quick_view_enabled` is true, then we have to make Quick View readonly. We have `editable` field in Annotation, but every annotation select makes it editable again. So we will override this on every select by condition.

### PR fulfills these requirements
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
- [x] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

#### What alternative approaches were there?
We could use `readonly` field, but it doesn't affect buttons for example.

#### What feature flags were used to cover this change?
No FF, just an org field `read_only_quick_view_enabled`.

### Does this PR introduce a breaking change?
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### CODE REVIEW

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11470739881)
> Successfully merged:  create mode 100644 web/libs/editor/tests/integration/e2e/relations/audio.cy.ts

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed.
> [Workflow run](https://github.com/HumanSignal/label-studio-enterprise/actions/runs/11470769689)

**Review by Gondragos — APPROVED** [review]

**Comment by MihajloHoma** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11501001009)
> Successfully merged:  create mode 100644 web/apps/labelstudio/src/pages/DataManager/api-config.example.js

**Comment by MihajloHoma** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11512801034)
> Successfully merged:  15 files changed, 169 insertions(+), 33 deletions(-)

**Comment by hlomzik** [comment]
/git merge
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/11565122995)
> Successfully merged:  19 files changed, 75 insertions(+), 39 deletions(-)

**Pull request merged**
